# Linux Kernel directorty
KDIR=../linux
# Directory to install dtb files to
INSTALL_DIR=/tftproot
# Cross-compile prefix
CROSS_COMPILE=armv7a-hardfloat-linux-gnueabi-
# gcc
CC=gcc

DTS = $(wildcard *.dts)
DTB = $(DTS:%.dts=%.dtb)

.PHONY: all
all: $(DTB)

$(DTB): %.dtb: %.dts
	@echo "  CC      $<"

# 	use gcc preprocessor to #include-style includes
	@$(CROSS_COMPILE)$(CC) \
	-E \
	-nostdinc \
	-I$(KDIR)/arch/arm/boot/dts \
	-I$(KDIR)/arch/arm/boot/dts/include \
	-I$(KDIR)/drivers/of/testcase-data \
	-undef \
	-D__DTS__ \
	-x assembler-with-cpp \
	-o .$<.pre \
	$<

# 	actually compile the dts
	@ $(KDIR)/scripts/dtc/dtc \
	-O dtb \
	-o $@ \
	-b 0 \
	-i . \
	-i $(KDIR)/arch/arm/boot/dts \
	.$<.pre

# 	remove temporary file generated by preprocessor
	@ rm .$<.pre

INSTALL_DTB = $(addprefix install-,${DTB})
.PHONY: $(INSTALL_DTB)
$(INSTALL_DTB): install-%:
	@echo "  INSTALL $*"	
	@cp $* $(INSTALL_DIR)/

.PHONY: install
install: $(INSTALL_DTB)

.PHONY: clean
clean:
#	delete all preprocessor generated files (if there are any ;)
	@echo "  CLEAN   $(PWD)"
	@rm -f *.dts.pre
	@rm -f $(DTB)
